name: Deploy test
on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy image to Yandex Cloud
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.YACLOUD_HOST }}
          username: ${{ secrets.YACLOUD_USER }}
          key: ${{ secrets.SSH_KEY }}
          scripts: |
            sudo docker pull taymir007/flaskapp

